# Generated by Django 3.2.4 on 2021-07-01 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='survey',
            table='tbl_survey',
        ),
    ]
