# Generated by Django 3.2.4 on 2021-07-01 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20210701_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(blank=True, help_text='Chọn khảo sát', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='survey.survey'),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(blank=True, help_text='Hãy điền câu hỏi ở đây!', max_length=255, null=True, verbose_name='Câu hỏi'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(blank=True, help_text='Hãy điền tên khảo sát ở đây!', max_length=255, null=True, verbose_name='Câu khảo sát!'),
        ),
    ]
