# Generated by Django 3.2.4 on 2021-07-01 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20210701_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, help_text='Hãy điền câu trả lời ở đây!', max_length=255, null=True, verbose_name='Câu trả lời')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('question', models.ForeignKey(blank=True, help_text='Chọn khảo sát', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer', to='survey.survey')),
            ],
            options={
                'verbose_name': 'Câu trả lời',
                'verbose_name_plural': 'Câu trả lời',
                'db_table': 'tbl_answer',
            },
        ),
    ]
