# Generated by Django 3.2.4 on 2021-07-01 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_alter_answer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/images/%Y/%m/%d')),
                ('h', models.FloatField(blank=True, default=0, null=True)),
                ('w', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'tbl_image',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_images', to='survey.image'),
        ),
    ]
